LRQA-82558
ViniLopes20/liferay-portal pull request #175
Opened 2023-09-06 20:06 UTC by crislucas1

2023-09-06 20:07 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-06 20:17 UTC, crislucas1 commented
ci:test:sf

2023-09-06 20:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7100/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7100/jenkins-report.html">here</a>.</b></p>

2023-09-06 20:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/954bb64877eb53b63d7ed5385dca27279761e861">954bb64877eb53b63d7ed5385dca27279761e861</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-82558">LRQA-82558</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/d6b6e6d6f8cd0892a90a50c53fb659ea423f8254">d6b6e6d6f8cd0892a90a50c53fb659ea423f8254</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7100/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7100/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7100/">test-portal-source-format#7100</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7100/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/175">ViniLopes20#175</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419833321">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#175 - 2023-09-06[13:17:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4348/">publish-testray-report#4348</a><br/></div></div>

2023-09-08 14:39 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/mytests/MyTestFile.macro
> +	macro changeScreenSize {
Hey @crislucas1, I think you could modify the name of this macro. For the macro that has a `change` term in the name, it seems to me that the macro is already going to **edit** some information on the page and what you want here is that it just **"Going to simulation > clicking custom"**. So I think you could put another name like `openCustomSimulation` or `goToCustomSimulation` or another idea more following verbs that are **navigation**

2023-09-08 14:42 UTC, ViniLopes20 requested changes
Hey @crislucas1, you must have a commit for each macro and path created and not a single commit for the file you created. I'm going to teach you later today a really cool way to separate the code when you have a lot of modifications in the same file. I forgot to show this to you earlier. Leave to correct this PR during our sync today.

Again these are small and simple corrections. Great job again here, congratulations Cristiano 🎉

2023-09-08 14:54 UTC, crislucas1 commented
ok, thanks for the feedback @ViniLopes20

2023-09-08 18:32 UTC, crislucas1 commented
ci:test:sf

2023-09-08 18:32 UTC, crislucas1 commented
ci:test:sf

2023-09-08 18:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8090/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8090/jenkins-report.html">here</a>.</b></p>

2023-09-08 18:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b33728b0d290dc5fec3abb2cbec217daa800992c">b33728b0d290dc5fec3abb2cbec217daa800992c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-82558">LRQA-82558</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/393808ef2a13625f7c0a106edb40ef6332bd6ca6">393808ef2a13625f7c0a106edb40ef6332bd6ca6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8090/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8090/jenkins-report.html">here</a>.</h5></details></html>

2023-09-08 18:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8090/">test-portal-source-format#8090</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8090/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/175">ViniLopes20#175</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2421166783">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#175 - 2023-09-08[11:33:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/30722/">publish-testray-report#30722</a><br/></div></div>

2023-09-08 18:47 UTC, ViniLopes20 approved these changes
Very good, Christian. Congrats on working on it 🎉

2023-09-08 18:47 UTC, closed without merging