LRQA-82564
ViniLopes20/liferay-portal pull request #179
Opened 2023-09-18 20:29 UTC by crislucas1

2023-09-18 20:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-18 20:32 UTC, crislucas1 commented
ci:test:sf

2023-09-18 20:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4850/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4850/jenkins-report.html">here</a>.</b></p>

2023-09-18 20:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f052fc2da8355f558ace46e9f116ef5cbc723d3b">f052fc2da8355f558ace46e9f116ef5cbc723d3b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-82564">LRQA-82564</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/330de902ddb3ef18f6a7874aefca181c50c41f95">330de902ddb3ef18f6a7874aefca181c50c41f95</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4850/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4850/jenkins-report.html">here</a>.</h5></details></html>

2023-09-18 20:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4850/">test-portal-source-format#4850</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4850/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/179">ViniLopes20#179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2426693584">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#179 - 2023-09-18[13:32:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4622/">publish-testray-report#4622</a><br/></div></div>

2023-09-19 13:37 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +		}
Hey @crislucas1, I think this step is already in your `setUp`, I think I might not need to repeat it here again. What do you think?

2023-09-19 13:39 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/MyBlogTests/MyBlogTests.testcase
> +				siteName = "Guest");
Hey @crislucas1, when you validate that the blogs are present on the page, you are already accessing the Blogs Page page at that moment. I don't think it's necessary to put this navigation here again. What do you think?

2023-09-19 13:41 UTC, ViniLopes20 requested changes
Hey @crislucas1, could you check my comments above? Remember to always review your test to check if all the macros/steps you added make sense or not. Sometimes we add a repeated step that does not affect the test result, but it may not make sense to repeat it and make the code longer

2023-09-19 14:16 UTC, crislucas1 commented
Right, thanks @ViniLopes20 . I'll correct

2023-09-19 14:34 UTC, crislucas1 commented
ci:test:sf

2023-09-19 14:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66f5e68aa216cf4ba1127a0a4f5f923237b0fcb7">66f5e68aa216cf4ba1127a0a4f5f923237b0fcb7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-82564">LRQA-82564</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/0fc717f32661f2c524df8cbdc48ef9110b094dee">0fc717f32661f2c524df8cbdc48ef9110b094dee</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7246/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7246/jenkins-report.html">here</a>.</h5></details></html>

2023-09-19 14:44 UTC, closed without merging

2023-09-19 14:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7246/">test-portal-source-format#7246</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7246/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/179">ViniLopes20#179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2427408084">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#179 - 2023-09-19[07:38:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3434/">publish-testray-report#3434</a><br/></div></div>