LRQA-83047
ViniLopes20/liferay-portal pull request #183
Opened 2023-09-22 21:55 UTC by crislucas1

2023-09-22 21:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-22 21:59 UTC, crislucas1 commented
ci:test:sf

2023-09-22 22:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">here</a>.</b></p>

2023-09-22 22:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-83047">LRQA-83047</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/cab1080a1c308e15debcd0cb454ea4416d8602be">cab1080a1c308e15debcd0cb454ea4416d8602be</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">here</a>.</h5></details></html>

2023-09-22 22:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format#4897</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/183">ViniLopes20#183</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2429848937">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#183 - 2023-09-22[15:01:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4679/">publish-testray-report#4679</a><br/></div></div>

2023-09-25 13:23 UTC, ViniLopes20 requested changes

2023-09-25 19:37 UTC, crislucas1 commented
ci:test:sf

2023-09-25 19:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4901/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4901/jenkins-report.html">here</a>.</b></p>

2023-09-25 19:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/crislucas1/liferay-portal/tree/LRQA-83047">LRQA-83047</a><br/>Branch GIT ID: <a href="https://github.com/crislucas1/liferay-portal/commit/291661a726672f75932b7ae8429ac2698fdfac1e">291661a726672f75932b7ae8429ac2698fdfac1e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4901/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4901/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 19:45 UTC, ViniLopes20 approved these changes
Very good, @crislucas1. Thanks for working on this. Congratulations 🎉

2023-09-25 19:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4901/">test-portal-source-format#4901</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4901/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ViniLopes20/liferay-portal/pull/183">ViniLopes20#183</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430588464">[master] ci:test:sf - crislucas1 &gt; ViniLopes20 - PR#183 - 2023-09-25[12:37:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4691/">publish-testray-report#4691</a><br/></div></div>

2023-09-25 19:46 UTC, closed without merging